title = "Getafix's Blog"
baseURL = "https://sabirmostofa.github.io"
languageCode = "en-us"
theme = ["beautifulhugo", "hugo-notice"]
publishDir = "docs"



DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-16165864-7"
enableRobotsTXT = true
disqusShortname= "localhost-tuxibvqizw"

[Sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Params]
  #homeTitle = "RESEARCHUT" # Set a different text for the header on the home page
  homeTitle = " "

  logo = "img/Logo_Blog_White.png"
  #logo = "img/Logo_druid.png"
  favicon = "img/Favicon.png"
  site_logo = "img/Logo_Blog_White.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/hellofoodbangladesh"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gold"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  comments = true
  #tells hugo to list posts in the main section
   mainSections = ["post" ]
   readingTime = true
  

  
 # [Params.staticman]
    pulls = "https://github.com/sabirmostofa/sabirmostofa.github.io/pulls"
  #3 versions work , choose one. 2nd one is from the staticman itself
  #api = "https://staticman3.herokuapp.com/v3/entry/github/sabirmostofa/sabirmostofa.github.io/master/comments"
     
  #api = "https://api.staticman.net/v3/entry/github/sabirmostofa/sabirmostofa.github.io/master/comments"
  # this one uses the fixted staticman version from https://github.com/sabirmostofa/staticman
  
  api = "https://staticman-hero.herokuapp.com/v3/entry/github/sabirmostofa/sabirmostofa.github.io/master/comments"
  
  #this one uses old version of staticman
  #api = "https://stat-dev.herokuapp.com/v3/entry/github/sabirmostofa/sabirmostofa.github.io/master/comments"
  
  #[Params.staticman.recaptcha]
      sitekey = "6LdOKL8ZAAAAAIVFJYu1b0VI6oyZQiKW3EKZm__t"      
      secret= "t4GqbyemHym2IucrAZlfCvwTVYjhkHLkumSttO0rMV+XM00zR4+xI5gDgPI65Gdg4IJ7chT55/D5GOkcTbXuD2J+40ICA8HrTHlxw9k2Cbx4eRN/xuPbWCxpxwNIozWjWMMRApYXeI2b7yWYl2/HkVWjnMMSkFLoxIN+x3/zLL8FDPRdjRd2KTmp9d/CdiJ7xA7XwujCxIMYWM9fWZldqeiHda2+5MnNj4OMFlZXzLzIywPT2xwdxWZUJZeo1N97pJGjwINojk/kr9oJPw7fMz0eMr0png4E6B4YdfPMZIxMPBwSuJh3GvwaXW+aQh0uVKrPrfQ2g+FXwPtVi6+Z1aWnRsycwmio1gdmCT2nsuCRcg4aB70AgT82/Xvqwg9H6wBOSxxvHRvOCUIX2hO1e8tx1roqkN6eTTg7XuD7KfVFUsk3RTaYMLpCxLR1Ycu3PlOasOxndOkEusN3FAKHQXfdE9zmftXhaAL2JZAVEKKef6r/0qaUuHL9wiQie/LKEMaKMble8cprdzMS6yUIJQt4txbuzxIkerI6KbD4ZkIUYhapRZrTbUDjcAR8w5jfz2n5SIpAhPDqSel51P5Utd9FO/BogdISy4qg/1G/EkKbslQtmFz352PkSR1lF5fX31Iu9Gjy5trXTMzVbJ5pEcwD2auSH3YeF/KX/KMWNu4="
  
