title = "Getafix's Blog"
baseURL = "https://sabirmostofa.github.io"
languageCode = "en-us"
theme = "beautifulhugo"
publishDir = "docs"



DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-16165864-7"
enableRobotsTXT = true
# disqusShortname= "localhost-tuxibvqizw"

[Sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Params]
  #homeTitle = "RESEARCHUT" # Set a different text for the header on the home page
  homeTitle = " "

  logo = "img/Logo_Blog_White.png"
  #logo = "img/Logo_druid.png"
  favicon = "img/Favicon.png"
  site_logo = "img/Logo_Blog_White.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = "https://www.facebook.com/hellofoodbangladesh"
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gold"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  comments = true
  #tells hugo to list posts in the main section
   mainSections = ["post" ]
   readingTime = true
  

  
  [Params.staticman]
  #3 versions work , choose one. 2nd one is from the staticman itself
  #api = "https://staticman3.herokuapp.com/v3/entry/github/sabirmostofa/sabirmostofa.github.io/master/comments"
     
    api = "https://api.staticman.net/v3/entry/github/sabirmostofa/sabirmostofa.github.io/master/comments"
  # this one uses the fixted staticman version from https://github.com/sabirmostofa/staticman
  
  #api = "https://staticman-hero.herokuapp.com/v3/entry/github/sabirmostofa/sabirmostofa.github.io/master/comments"
  
  #this one uses old version of staticman
  #api = "https://stat-dev.herokuapp.com/v3/entry/github/sabirmostofa/sabirmostofa.github.io/master/comments"
  
  [Params.staticman.recaptcha]
      sitekey = "6LfbVr8ZAAAAANytNf0XdnqfLnwvBp9tE04DoNW_"      
      secret= "NhSEc9y6+R76KfU/OrAg7DirsFY/35EtCLjMslWnCLw+R9vaQB3c4h/j97TdQqK4T67eJQj/GM/ARYiXcjLESJ8EcA79lDlnKGCJjKY5atgzPM1Grf9QZnJd/u499MdibFstsUxYg+jlp1L4S5tNWFXNO6W0FJeEapiSI8THvEw="
  
